<?xml version="1.0"?>
<package format="2">
  <name>my_rb1_description</name>
  <version>1.0.0</version>
  <description>RB1 Robot Description for ROS 1</description>
  <maintainer email="sharifaiub15@gmail.com">Shariful</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <depend>urdf</depend>
  <depend>xacro</depend>
</package>